#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invdep
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="investment_companies_db")]
	public partial class MyDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertPhysical_Person(Physical_Person instance);
    partial void UpdatePhysical_Person(Physical_Person instance);
    partial void DeletePhysical_Person(Physical_Person instance);
    partial void InsertCompanies_Share(Companies_Share instance);
    partial void UpdateCompanies_Share(Companies_Share instance);
    partial void DeleteCompanies_Share(Companies_Share instance);
    partial void InsertCompany_type(Company_type instance);
    partial void UpdateCompany_type(Company_type instance);
    partial void DeleteCompany_type(Company_type instance);
    partial void InsertMethod(Method instance);
    partial void UpdateMethod(Method instance);
    partial void DeleteMethod(Method instance);
    #endregion
		
		public MyDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["investment_companies_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<Physical_Person> Physical_Persons
		{
			get
			{
				return this.GetTable<Physical_Person>();
			}
		}
		
		public System.Data.Linq.Table<Companies_Share> Companies_Shares
		{
			get
			{
				return this.GetTable<Companies_Share>();
			}
		}
		
		public System.Data.Linq.Table<Company_type> Company_types
		{
			get
			{
				return this.GetTable<Company_type>();
			}
		}
		
		public System.Data.Linq.Table<Method> Methods
		{
			get
			{
				return this.GetTable<Method>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Companies")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Company_Name;
		
		private string _Capital;
		
		private string _Seat;
		
		private System.Nullable<System.DateTime> _Date_of_Signature_of_APOLS;
		
		private System.Nullable<System.DateTime> _Date_Of_Signature_Of_Company_Documents;
		
		private System.Nullable<System.DateTime> _Date_Of_First_Payment;
		
		private System.Nullable<System.DateTime> _Date_Of_Second_Payment;
		
		private System.Nullable<System.DateTime> _Date_Of_Residence_Payment;
		
		private string _Notes;
		
		private System.Nullable<int> _Contact_Parson;
		
		private System.Nullable<int> _Company_Type;
		
		private System.Nullable<int> _Method;
		
		private System.Nullable<int> _Eligable_MD_If_Exists;
		
		private EntitySet<Companies_Share> _Companies_Shares;
		
		private EntityRef<Physical_Person> _The_Contact_Person;
		
		private EntityRef<Physical_Person> _The_Managing_Director;
		
		private EntityRef<Company_type> _The_Company_type;
		
		private EntityRef<Method> _Process_Method;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCompany_NameChanging(string value);
    partial void OnCompany_NameChanged();
    partial void OnCapitalChanging(string value);
    partial void OnCapitalChanged();
    partial void OnSeatChanging(string value);
    partial void OnSeatChanged();
    partial void OnDate_of_Signature_of_APOLSChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_Signature_of_APOLSChanged();
    partial void OnDate_Of_Signature_Of_Company_DocumentsChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_Of_Signature_Of_Company_DocumentsChanged();
    partial void OnDate_Of_First_PaymentChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_Of_First_PaymentChanged();
    partial void OnDate_Of_Second_PaymentChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_Of_Second_PaymentChanged();
    partial void OnDate_Of_Residence_PaymentChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_Of_Residence_PaymentChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnContact_ParsonChanging(System.Nullable<int> value);
    partial void OnContact_ParsonChanged();
    partial void OnCompany_TypeChanging(System.Nullable<int> value);
    partial void OnCompany_TypeChanged();
    partial void OnMethodChanging(System.Nullable<int> value);
    partial void OnMethodChanged();
    partial void OnEligable_MD_If_ExistsChanging(System.Nullable<int> value);
    partial void OnEligable_MD_If_ExistsChanged();
    #endregion
		
		public Company()
		{
			this._Companies_Shares = new EntitySet<Companies_Share>(new Action<Companies_Share>(this.attach_Companies_Shares), new Action<Companies_Share>(this.detach_Companies_Shares));
			this._The_Contact_Person = default(EntityRef<Physical_Person>);
			this._The_Managing_Director = default(EntityRef<Physical_Person>);
			this._The_Company_type = default(EntityRef<Company_type>);
			this._Process_Method = default(EntityRef<Method>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Name", DbType="NVarChar(50)")]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this.OnCompany_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Name = value;
					this.SendPropertyChanged("Company_Name");
					this.OnCompany_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="NVarChar(50)")]
		public string Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat", DbType="NVarChar(50)")]
		public string Seat
		{
			get
			{
				return this._Seat;
			}
			set
			{
				if ((this._Seat != value))
				{
					this.OnSeatChanging(value);
					this.SendPropertyChanging();
					this._Seat = value;
					this.SendPropertyChanged("Seat");
					this.OnSeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Signature_of_APOLS", DbType="Date")]
		public System.Nullable<System.DateTime> Date_of_Signature_of_APOLS
		{
			get
			{
				return this._Date_of_Signature_of_APOLS;
			}
			set
			{
				if ((this._Date_of_Signature_of_APOLS != value))
				{
					this.OnDate_of_Signature_of_APOLSChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Signature_of_APOLS = value;
					this.SendPropertyChanged("Date_of_Signature_of_APOLS");
					this.OnDate_of_Signature_of_APOLSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Signature_Of_Company_Documents", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Of_Signature_Of_Company_Documents
		{
			get
			{
				return this._Date_Of_Signature_Of_Company_Documents;
			}
			set
			{
				if ((this._Date_Of_Signature_Of_Company_Documents != value))
				{
					this.OnDate_Of_Signature_Of_Company_DocumentsChanging(value);
					this.SendPropertyChanging();
					this._Date_Of_Signature_Of_Company_Documents = value;
					this.SendPropertyChanged("Date_Of_Signature_Of_Company_Documents");
					this.OnDate_Of_Signature_Of_Company_DocumentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_First_Payment", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Of_First_Payment
		{
			get
			{
				return this._Date_Of_First_Payment;
			}
			set
			{
				if ((this._Date_Of_First_Payment != value))
				{
					this.OnDate_Of_First_PaymentChanging(value);
					this.SendPropertyChanging();
					this._Date_Of_First_Payment = value;
					this.SendPropertyChanged("Date_Of_First_Payment");
					this.OnDate_Of_First_PaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Second_Payment", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Of_Second_Payment
		{
			get
			{
				return this._Date_Of_Second_Payment;
			}
			set
			{
				if ((this._Date_Of_Second_Payment != value))
				{
					this.OnDate_Of_Second_PaymentChanging(value);
					this.SendPropertyChanging();
					this._Date_Of_Second_Payment = value;
					this.SendPropertyChanged("Date_Of_Second_Payment");
					this.OnDate_Of_Second_PaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Residence_Payment", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Of_Residence_Payment
		{
			get
			{
				return this._Date_Of_Residence_Payment;
			}
			set
			{
				if ((this._Date_Of_Residence_Payment != value))
				{
					this.OnDate_Of_Residence_PaymentChanging(value);
					this.SendPropertyChanging();
					this._Date_Of_Residence_Payment = value;
					this.SendPropertyChanged("Date_Of_Residence_Payment");
					this.OnDate_Of_Residence_PaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_Parson", DbType="Int")]
		public System.Nullable<int> Contact_Parson
		{
			get
			{
				return this._Contact_Parson;
			}
			set
			{
				if ((this._Contact_Parson != value))
				{
					if (this._The_Contact_Person.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnContact_ParsonChanging(value);
					this.SendPropertyChanging();
					this._Contact_Parson = value;
					this.SendPropertyChanged("Contact_Parson");
					this.OnContact_ParsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Type", DbType="Int")]
		public System.Nullable<int> Company_Type
		{
			get
			{
				return this._Company_Type;
			}
			set
			{
				if ((this._Company_Type != value))
				{
					if (this._The_Company_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompany_TypeChanging(value);
					this.SendPropertyChanging();
					this._Company_Type = value;
					this.SendPropertyChanged("Company_Type");
					this.OnCompany_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Method", DbType="Int")]
		public System.Nullable<int> Method
		{
			get
			{
				return this._Method;
			}
			set
			{
				if ((this._Method != value))
				{
					if (this._Process_Method.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMethodChanging(value);
					this.SendPropertyChanging();
					this._Method = value;
					this.SendPropertyChanged("Method");
					this.OnMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eligable_MD_If_Exists", DbType="Int")]
		public System.Nullable<int> Eligable_MD_If_Exists
		{
			get
			{
				return this._Eligable_MD_If_Exists;
			}
			set
			{
				if ((this._Eligable_MD_If_Exists != value))
				{
					if (this._The_Managing_Director.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEligable_MD_If_ExistsChanging(value);
					this.SendPropertyChanging();
					this._Eligable_MD_If_Exists = value;
					this.SendPropertyChanged("Eligable_MD_If_Exists");
					this.OnEligable_MD_If_ExistsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Companies_Share", Storage="_Companies_Shares", ThisKey="ID", OtherKey="CompanyID")]
		public EntitySet<Companies_Share> Companies_Shares
		{
			get
			{
				return this._Companies_Shares;
			}
			set
			{
				this._Companies_Shares.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Company", Storage="_The_Contact_Person", ThisKey="Contact_Parson", OtherKey="ID", IsForeignKey=true)]
		public Physical_Person The_Contact_Person
		{
			get
			{
				return this._The_Contact_Person.Entity;
			}
			set
			{
				Physical_Person previousValue = this._The_Contact_Person.Entity;
				if (((previousValue != value) 
							|| (this._The_Contact_Person.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_Contact_Person.Entity = null;
						previousValue.Companies.Remove(this);
					}
					this._The_Contact_Person.Entity = value;
					if ((value != null))
					{
						value.Companies.Add(this);
						this._Contact_Parson = value.ID;
					}
					else
					{
						this._Contact_Parson = default(Nullable<int>);
					}
					this.SendPropertyChanged("The_Contact_Person");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Company1", Storage="_The_Managing_Director", ThisKey="Eligable_MD_If_Exists", OtherKey="ID", IsForeignKey=true)]
		public Physical_Person The_Managing_Director
		{
			get
			{
				return this._The_Managing_Director.Entity;
			}
			set
			{
				Physical_Person previousValue = this._The_Managing_Director.Entity;
				if (((previousValue != value) 
							|| (this._The_Managing_Director.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_Managing_Director.Entity = null;
						previousValue.Companies1.Remove(this);
					}
					this._The_Managing_Director.Entity = value;
					if ((value != null))
					{
						value.Companies1.Add(this);
						this._Eligable_MD_If_Exists = value.ID;
					}
					else
					{
						this._Eligable_MD_If_Exists = default(Nullable<int>);
					}
					this.SendPropertyChanged("The_Managing_Director");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_type_Company", Storage="_The_Company_type", ThisKey="Company_Type", OtherKey="ID", IsForeignKey=true)]
		public Company_type The_Company_type
		{
			get
			{
				return this._The_Company_type.Entity;
			}
			set
			{
				Company_type previousValue = this._The_Company_type.Entity;
				if (((previousValue != value) 
							|| (this._The_Company_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_Company_type.Entity = null;
						previousValue.Companies.Remove(this);
					}
					this._The_Company_type.Entity = value;
					if ((value != null))
					{
						value.Companies.Add(this);
						this._Company_Type = value.ID;
					}
					else
					{
						this._Company_Type = default(Nullable<int>);
					}
					this.SendPropertyChanged("The_Company_type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Method_Company", Storage="_Process_Method", ThisKey="Method", OtherKey="ID", IsForeignKey=true)]
		public Method Process_Method
		{
			get
			{
				return this._Process_Method.Entity;
			}
			set
			{
				Method previousValue = this._Process_Method.Entity;
				if (((previousValue != value) 
							|| (this._Process_Method.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Process_Method.Entity = null;
						previousValue.Companies.Remove(this);
					}
					this._Process_Method.Entity = value;
					if ((value != null))
					{
						value.Companies.Add(this);
						this._Method = value.ID;
					}
					else
					{
						this._Method = default(Nullable<int>);
					}
					this.SendPropertyChanged("Process_Method");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Companies_Shares(Companies_Share entity)
		{
			this.SendPropertyChanging();
			entity.The_Company_Name = this;
		}
		
		private void detach_Companies_Shares(Companies_Share entity)
		{
			this.SendPropertyChanging();
			entity.The_Company_Name = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Physical_Persons")]
	public partial class Physical_Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Full_Name_As_in_Passport;
		
		private System.Nullable<System.DateTime> _Birth_Date;
		
		private string _PassportNumber;
		
		private string _Nationality;
		
		private string _Permanent_Address;
		
		private string _Temp_Address;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _Residence_location;
		
		private string _Notes;
		
		private EntitySet<Company> _Companies;
		
		private EntitySet<Company> _Companies1;
		
		private EntitySet<Companies_Share> _Companies_Shares;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFull_Name_As_in_PassportChanging(string value);
    partial void OnFull_Name_As_in_PassportChanged();
    partial void OnBirth_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirth_DateChanged();
    partial void OnPassportNumberChanging(string value);
    partial void OnPassportNumberChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnPermanent_AddressChanging(string value);
    partial void OnPermanent_AddressChanged();
    partial void OnTemp_AddressChanging(string value);
    partial void OnTemp_AddressChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnResidence_locationChanging(string value);
    partial void OnResidence_locationChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Physical_Person()
		{
			this._Companies = new EntitySet<Company>(new Action<Company>(this.attach_Companies), new Action<Company>(this.detach_Companies));
			this._Companies1 = new EntitySet<Company>(new Action<Company>(this.attach_Companies1), new Action<Company>(this.detach_Companies1));
			this._Companies_Shares = new EntitySet<Companies_Share>(new Action<Companies_Share>(this.attach_Companies_Shares), new Action<Companies_Share>(this.detach_Companies_Shares));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name_As_in_Passport", DbType="NVarChar(200)")]
		public string Full_Name_As_in_Passport
		{
			get
			{
				return this._Full_Name_As_in_Passport;
			}
			set
			{
				if ((this._Full_Name_As_in_Passport != value))
				{
					this.OnFull_Name_As_in_PassportChanging(value);
					this.SendPropertyChanging();
					this._Full_Name_As_in_Passport = value;
					this.SendPropertyChanged("Full_Name_As_in_Passport");
					this.OnFull_Name_As_in_PassportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birth_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Birth_Date
		{
			get
			{
				return this._Birth_Date;
			}
			set
			{
				if ((this._Birth_Date != value))
				{
					this.OnBirth_DateChanging(value);
					this.SendPropertyChanging();
					this._Birth_Date = value;
					this.SendPropertyChanged("Birth_Date");
					this.OnBirth_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNumber", DbType="NVarChar(50)")]
		public string PassportNumber
		{
			get
			{
				return this._PassportNumber;
			}
			set
			{
				if ((this._PassportNumber != value))
				{
					this.OnPassportNumberChanging(value);
					this.SendPropertyChanging();
					this._PassportNumber = value;
					this.SendPropertyChanged("PassportNumber");
					this.OnPassportNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permanent_Address", DbType="NVarChar(50)")]
		public string Permanent_Address
		{
			get
			{
				return this._Permanent_Address;
			}
			set
			{
				if ((this._Permanent_Address != value))
				{
					this.OnPermanent_AddressChanging(value);
					this.SendPropertyChanging();
					this._Permanent_Address = value;
					this.SendPropertyChanged("Permanent_Address");
					this.OnPermanent_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temp_Address", DbType="NVarChar(50)")]
		public string Temp_Address
		{
			get
			{
				return this._Temp_Address;
			}
			set
			{
				if ((this._Temp_Address != value))
				{
					this.OnTemp_AddressChanging(value);
					this.SendPropertyChanging();
					this._Temp_Address = value;
					this.SendPropertyChanged("Temp_Address");
					this.OnTemp_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="NVarChar(50)")]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this.OnPhone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Phone_Number = value;
					this.SendPropertyChanged("Phone_Number");
					this.OnPhone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residence_location", DbType="NVarChar(50)")]
		public string Residence_location
		{
			get
			{
				return this._Residence_location;
			}
			set
			{
				if ((this._Residence_location != value))
				{
					this.OnResidence_locationChanging(value);
					this.SendPropertyChanging();
					this._Residence_location = value;
					this.SendPropertyChanged("Residence_location");
					this.OnResidence_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Company", Storage="_Companies", ThisKey="ID", OtherKey="Contact_Parson")]
		public EntitySet<Company> Companies
		{
			get
			{
				return this._Companies;
			}
			set
			{
				this._Companies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Company1", Storage="_Companies1", ThisKey="ID", OtherKey="Eligable_MD_If_Exists")]
		public EntitySet<Company> Companies1
		{
			get
			{
				return this._Companies1;
			}
			set
			{
				this._Companies1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Companies_Share", Storage="_Companies_Shares", ThisKey="ID", OtherKey="ShareHolderID")]
		public EntitySet<Companies_Share> Companies_Shares
		{
			get
			{
				return this._Companies_Shares;
			}
			set
			{
				this._Companies_Shares.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Contact_Person = this;
		}
		
		private void detach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Contact_Person = null;
		}
		
		private void attach_Companies1(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Managing_Director = this;
		}
		
		private void detach_Companies1(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Managing_Director = null;
		}
		
		private void attach_Companies_Shares(Companies_Share entity)
		{
			this.SendPropertyChanging();
			entity.Shareholder = this;
		}
		
		private void detach_Companies_Shares(Companies_Share entity)
		{
			this.SendPropertyChanging();
			entity.Shareholder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Companies_Shares")]
	public partial class Companies_Share : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompanyID;
		
		private int _ShareHolderID;
		
		private System.Nullable<int> _Share_Amount_in_EURO;
		
		private System.Nullable<bool> _Wants_To_Be_MD;
		
		private System.Nullable<bool> _Is_Already_MD;
		
		private System.Nullable<bool> _Already_Got_Residence;
		
		private EntityRef<Company> _The_Company_Name;
		
		private EntityRef<Physical_Person> _Shareholder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyIDChanging(int value);
    partial void OnCompanyIDChanged();
    partial void OnShareHolderIDChanging(int value);
    partial void OnShareHolderIDChanged();
    partial void OnShare_Amount_in_EUROChanging(System.Nullable<int> value);
    partial void OnShare_Amount_in_EUROChanged();
    partial void OnWants_To_Be_MDChanging(System.Nullable<bool> value);
    partial void OnWants_To_Be_MDChanged();
    partial void OnIs_Already_MDChanging(System.Nullable<bool> value);
    partial void OnIs_Already_MDChanged();
    partial void OnAlready_Got_ResidenceChanging(System.Nullable<bool> value);
    partial void OnAlready_Got_ResidenceChanged();
    #endregion
		
		public Companies_Share()
		{
			this._The_Company_Name = default(EntityRef<Company>);
			this._Shareholder = default(EntityRef<Physical_Person>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					if (this._The_Company_Name.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShareHolderID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ShareHolderID
		{
			get
			{
				return this._ShareHolderID;
			}
			set
			{
				if ((this._ShareHolderID != value))
				{
					if (this._Shareholder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShareHolderIDChanging(value);
					this.SendPropertyChanging();
					this._ShareHolderID = value;
					this.SendPropertyChanged("ShareHolderID");
					this.OnShareHolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Share_Amount_in_EURO", DbType="Int")]
		public System.Nullable<int> Share_Amount_in_EURO
		{
			get
			{
				return this._Share_Amount_in_EURO;
			}
			set
			{
				if ((this._Share_Amount_in_EURO != value))
				{
					this.OnShare_Amount_in_EUROChanging(value);
					this.SendPropertyChanging();
					this._Share_Amount_in_EURO = value;
					this.SendPropertyChanged("Share_Amount_in_EURO");
					this.OnShare_Amount_in_EUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wants_To_Be_MD", DbType="Bit")]
		public System.Nullable<bool> Wants_To_Be_MD
		{
			get
			{
				return this._Wants_To_Be_MD;
			}
			set
			{
				if ((this._Wants_To_Be_MD != value))
				{
					this.OnWants_To_Be_MDChanging(value);
					this.SendPropertyChanging();
					this._Wants_To_Be_MD = value;
					this.SendPropertyChanged("Wants_To_Be_MD");
					this.OnWants_To_Be_MDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Already_MD", DbType="Bit")]
		public System.Nullable<bool> Is_Already_MD
		{
			get
			{
				return this._Is_Already_MD;
			}
			set
			{
				if ((this._Is_Already_MD != value))
				{
					this.OnIs_Already_MDChanging(value);
					this.SendPropertyChanging();
					this._Is_Already_MD = value;
					this.SendPropertyChanged("Is_Already_MD");
					this.OnIs_Already_MDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Already_Got_Residence", DbType="Bit")]
		public System.Nullable<bool> Already_Got_Residence
		{
			get
			{
				return this._Already_Got_Residence;
			}
			set
			{
				if ((this._Already_Got_Residence != value))
				{
					this.OnAlready_Got_ResidenceChanging(value);
					this.SendPropertyChanging();
					this._Already_Got_Residence = value;
					this.SendPropertyChanged("Already_Got_Residence");
					this.OnAlready_Got_ResidenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Companies_Share", Storage="_The_Company_Name", ThisKey="CompanyID", OtherKey="ID", IsForeignKey=true)]
		public Company The_Company_Name
		{
			get
			{
				return this._The_Company_Name.Entity;
			}
			set
			{
				Company previousValue = this._The_Company_Name.Entity;
				if (((previousValue != value) 
							|| (this._The_Company_Name.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_Company_Name.Entity = null;
						previousValue.Companies_Shares.Remove(this);
					}
					this._The_Company_Name.Entity = value;
					if ((value != null))
					{
						value.Companies_Shares.Add(this);
						this._CompanyID = value.ID;
					}
					else
					{
						this._CompanyID = default(int);
					}
					this.SendPropertyChanged("The_Company_Name");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Physical_Person_Companies_Share", Storage="_Shareholder", ThisKey="ShareHolderID", OtherKey="ID", IsForeignKey=true)]
		public Physical_Person Shareholder
		{
			get
			{
				return this._Shareholder.Entity;
			}
			set
			{
				Physical_Person previousValue = this._Shareholder.Entity;
				if (((previousValue != value) 
							|| (this._Shareholder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Shareholder.Entity = null;
						previousValue.Companies_Shares.Remove(this);
					}
					this._Shareholder.Entity = value;
					if ((value != null))
					{
						value.Companies_Shares.Add(this);
						this._ShareHolderID = value.ID;
					}
					else
					{
						this._ShareHolderID = default(int);
					}
					this.SendPropertyChanged("Shareholder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company_types")]
	public partial class Company_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Company_Type_Name;
		
		private string _Description;
		
		private EntitySet<Company> _Companies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCompany_Type_NameChanging(string value);
    partial void OnCompany_Type_NameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public Company_type()
		{
			this._Companies = new EntitySet<Company>(new Action<Company>(this.attach_Companies), new Action<Company>(this.detach_Companies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Type_Name", DbType="NVarChar(50)")]
		public string Company_Type_Name
		{
			get
			{
				return this._Company_Type_Name;
			}
			set
			{
				if ((this._Company_Type_Name != value))
				{
					this.OnCompany_Type_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Type_Name = value;
					this.SendPropertyChanged("Company_Type_Name");
					this.OnCompany_Type_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_type_Company", Storage="_Companies", ThisKey="ID", OtherKey="Company_Type")]
		public EntitySet<Company> Companies
		{
			get
			{
				return this._Companies;
			}
			set
			{
				this._Companies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Company_type = this;
		}
		
		private void detach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.The_Company_type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Methods")]
	public partial class Method : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Method_Name;
		
		private string _Description;
		
		private EntitySet<Company> _Companies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMethod_NameChanging(string value);
    partial void OnMethod_NameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public Method()
		{
			this._Companies = new EntitySet<Company>(new Action<Company>(this.attach_Companies), new Action<Company>(this.detach_Companies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Method_Name", DbType="NVarChar(50)")]
		public string Method_Name
		{
			get
			{
				return this._Method_Name;
			}
			set
			{
				if ((this._Method_Name != value))
				{
					this.OnMethod_NameChanging(value);
					this.SendPropertyChanging();
					this._Method_Name = value;
					this.SendPropertyChanged("Method_Name");
					this.OnMethod_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Method_Company", Storage="_Companies", ThisKey="ID", OtherKey="Method")]
		public EntitySet<Company> Companies
		{
			get
			{
				return this._Companies;
			}
			set
			{
				this._Companies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.Process_Method = this;
		}
		
		private void detach_Companies(Company entity)
		{
			this.SendPropertyChanging();
			entity.Process_Method = null;
		}
	}
}
#pragma warning restore 1591
